spring.datasource.driver-class-name=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
# FSS Financial Product API
fss.api.base-url=
fss.api.auth=
fss.api.deposit-path=
fss.api.saving-path=
fss.api.top-fin-grp-no=
fss.api.financial-company-code=
fss.api.page-no=
#jwt
jwt.secret=
jwt.access-token-expires-in=
jwt.refresh-token-expires-in=
#redis
redis.host=
redis.port=
redis.password=
redis.database=
redis.key-prefix.refresh-token=
#cors
cors.allowed-origins=
