# Development database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Development Redis
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT:6379}
redis.password=${REDIS_PASSWORD:}
redis.database=${REDIS_DATABASE:0}

# Development frontend
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
