# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Redis
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT:6379}
redis.password=${REDIS_PASSWORD}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# MyData Server
mydata.api.base-url=${MYDATA_API_BASE_URL}
