spring.datasource.driver-class-name=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
# FSS Financial Product API
fss.api.base-url=
fss.api.auth=
fss.api.deposit-path=
fss.api.saving-path=
fss.api.top-fin-grp-no=
fss.api.page-no=
